=== udayLexmark/packages/Contivo_Runtime/code/classes/com/contivo/runtime/core/messages.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by XML Authority. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
	<!-- A message file (.msg file)'s schema. -->
	
	<xs:element name = "Messages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name = "SupportedLocales" type = "SupportedLocales" minOccurs = "0"/>
				<xs:element name = "include" type = "include" minOccurs = "0" maxOccurs = "unbounded"/>
				<xs:element name = "Domain" type = "Domain" maxOccurs = "unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name = "SupportedLocales"/>
	<xs:complexType name = "include">
		<xs:attribute name = "src" use = "required" type = "xs:string"/>
	</xs:complexType>
	<xs:complexType name = "Domain">
		<!-- defaultLang will specify the language of the Message and
           SMessage contents that are not inside a translation.  This
           is useful if a .msg file contains primarily foreign
           language translations of messages whose defaults are
           defined elsewhere. -->
		<xs:choice maxOccurs = "unbounded">
			<xs:element name = "Message" type = "Message"/>
			<xs:element name = "SMessage" type = "SMessage"/>
		</xs:choice>
		<xs:attribute name = "name" use = "required" type = "xs:string"/>
		<xs:attribute name = "defaultLang" type = "xs:language"/>
	</xs:complexType>
	<xs:complexType name = "Message">
		<xs:sequence>
			<xs:element name = "Translation" type = "Translation" minOccurs = "0" maxOccurs = "unbounded"/>
		</xs:sequence>
		<xs:attribute name = "name" use = "required" type = "xs:NCName"/>
		<xs:attribute name = "text" use = "optional" type = "xs:string"/>
	</xs:complexType>
	<xs:complexType name = "SMessage">
		<xs:sequence>
			<xs:element ref = "Msg" minOccurs = "0"/>
			<xs:element name = "Translation" type = "STranslation" minOccurs = "0" maxOccurs = "unbounded"/>
		</xs:sequence>
		<xs:attribute name = "name" use = "required" type = "xs:NCName"/>
	</xs:complexType>
	<xs:complexType name = "Translation"/>
	<xs:complexType name = "STranslation">
		<xs:sequence>
			<xs:element ref = "Msg"/>
		</xs:sequence>
		<xs:attribute name = "lang" use = "required" type = "xs:language"/>
	</xs:complexType>
	<xs:element name = "Msg" type = "Msg"/>
	<xs:complexType name = "Msg">
		<xs:sequence>
			<xs:element ref = "Msg" minOccurs = "0" maxOccurs = "unbounded"/>
		</xs:sequence>
		<xs:attribute name = "class" use = "required" type = "MsgClass"/>
		<xs:attribute name = "header" type = "xs:string"/>
		<xs:attribute name = "text" type = "xs:string"/>
	</xs:complexType>
	<xs:simpleType name = "MsgClass">
		<xs:restriction base = "xs:NCName">
			<xs:enumeration value = "Input"/>
			<xs:enumeration value = "Output"/>
			<xs:enumeration value = "Both"/>
			<xs:enumeration value = "Other"/>
			<xs:enumeration value = "Exception"/>
			<xs:enumeration value = "Error"/>
			<xs:enumeration value = "Warning"/>
			<xs:enumeration value = "Value"/>
			<xs:enumeration value = "Suggestion"/>
			<xs:enumeration value = "String"/>
			<xs:enumeration value = "Number"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== udayLexmark/packages/Contivo_Runtime/code/classes/com/contivo/runtime/ffd/FFDResources.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<!--
# $Id: FFDResources.xml,v 1.1.2.6.8.1.2.2.4.1 2006/09/08 21:17:24 kmcafee Exp $
#
# Resource nomenclature:
# The key appears on the left-hand side of the = and the value on the right.  The value is
# the actual string that is to be fetched.  The key should reflect or resemble the value
# reasonably, and should only contain the characters [A-Za-z0-9_].  The key should have
#  as a prefix, and this prefix should NOT be followed by an underscore.
#
# The reason for this convention is that the key will typically appear in java source code
# as a string constant.  As such, the key will be indistinguishable from any other string.
# By following this convention, it will be simple for a person or a shell script to
# distinguish a key and an ordinary string constant.
#
# We avoid separating the  prefix from the key with an underscore (or any other
# separator) because doing so would impart a word boundary on that part of the key that
# would follow the _.  This would make it hard to write scripts to operate on strings that
# are not keys.
-->
<Messages xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "./messages.xsd">
    <Domain name = "ffd">
        <!-- Example Structured Message
            <SMessage name = "Message_ID">
                <Msg class = "Error" header = "Message_Category" text = "Text Description: {0}">
                    <Msg class = "String" header = "Structured Information" text = "value"/>
                    <Msg class = "String" header = "Structured Information2" text = "value2"/>
                </Msg>
            </SMessage>
        -->
        <SMessage name = "Tree_Field_IRENode_Has_No_Parent">
            <Msg class = "Other" header = "Internal_Error" text = "The IRENode {0} has no parent, and cannot generate XPath information.">
                <Msg class = "String" header = "IRENode Name" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "No_XPath_Bad_IRENode_Object_Type">
            <Msg class = "Other" header = "Internal_Error" text = "Could Not calculate XPath in IRENode due to unknown IRENode Object Type.">
                <Msg class = "String" header = "Object Type" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Pop_Mark_Out_Of_Range">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Ran out of marks in ModeStream.popMark(). Current byte offset at input stream: {0}">
                <Msg class = "String" header = "Current Byte Offset" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Flush_Mark_Out_Of_Range">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Ran out of marks in ModeStream.flushMark(). Current byte offset at input stream: {0}">
                <Msg class = "String" header = "Current Byte Offset" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Filter_Pattern_Illegal_Char">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Syntax error in filter pattern. Filter pattern: {0}">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Unbalanced_Binding">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} has unbalanced binding delimiters">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Filter_Pattern_Empty">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "One of the filter has empty pattern.">
            </Msg>
        </SMessage>
        <SMessage name = "Filter_Pattern_Missing">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "One of the filter has no pattern.">
            </Msg>
        </SMessage>
        <SMessage name = "Filter_Value_Missing">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "One of the filter has no pattern.">
            </Msg>
        </SMessage>
        <SMessage name = "Invalid_Character_Class">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with invalid character class.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Invalid_Char_Range">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with invalid character range.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Unterminated_Char_Range">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with unterminated character range.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Missing_Character_Class_Enclosing_Tag">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with missing character class enclosing tag.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Nested_Binding">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with nested binding.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Backslash_At_Pattern_End">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter patten {0} is malformed with backslash at the end.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Invalid_Hex_Char_In_Pattern">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern {0} is malformed with invalid hex character constant.">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Backslash_At_Value_End">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter replacement value {0} is malformed with backslash at the end.">
                <Msg class = "String" header = "Filter replacement value" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Invalid_Hex_Char_In_Value">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter replacement value {0} is malformed with invalid hex character constant.">
                <Msg class = "String" header = "Filter replacement value" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_Binding_Reference">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter replacement value {0} has illegal binding reference. Pattern has only {1} bindings.">
                <Msg class = "String" header = "Filter replacement value" text = "{0}"/>
                <Msg class = "String" header = "Filter pattern binding number" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_State_In_Regex_Match">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal state in filter pattern match. Filter pattern: {0}">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Miltiple_End_Binding_Steps">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Filter pattern has multiple end of binding steps. Filter pattern: {0}">
                <Msg class = "String" header = "Filter pattern" text = "{0}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_Boolean_Constant">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal boolean constant {0} specified for attribute @{1}">
                <Msg class = "String" header = "Boolean value" text = "{0}"/>
                <Msg class = "String" header = "Attribute name" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_Int_Constant">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal int constant {0} specified for attribute @{1}">
                <Msg class = "String" header = "int value" text = "{0}"/>
                <Msg class = "String" header = "Attribute name" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_String_Constant">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal String constant {0} specified for attribute @{1}">
                <Msg class = "String" header = "String value" text = "{0}"/>
                <Msg class = "String" header = "Attribute name" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_Hex_Constant">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal Hex constant {0} specified for attribute @{1}">
                <Msg class = "String" header = "Hex constant value" text = "{0}"/>
                <Msg class = "String" header = "Attribute name" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Illegal_Octal_Constant">
            <Msg class = "Other" header = "FFD_Processing_Error" text = "Illegal Octal constant {0} specified for attribute @{1}">
                <Msg class = "String" header = "Octal constant value" text = "{0}"/>
                <Msg class = "String" header = "Attribute name" text = "{1}"/>
            </Msg>
        </SMessage>
        <SMessage name = "Syntex_Undefined">
